/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Liveness check.
     */
    get: operations["health_api_v1_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/meta": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Meta
     * @description District, data mode, API version, demo issue dates (with labels), languages, crops, variables.
     */
    get: operations["meta_api_v1_meta_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/geo/panchayats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Panchayats
     * @description Panchayat polygons (synthetic Voronoi cells in mock mode).
     */
    get: operations["panchayats_api_v1_geo_panchayats_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/geo/blocks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Blocks
     * @description Block polygons (unions of the Panchayat cells in mock mode).
     */
    get: operations["blocks_api_v1_geo_blocks_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/forecast/map": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Forecast Map
     * @description Block layer and Panchayat layer for one variable and lead day.
     */
    get: operations["forecast_map_api_v1_forecast_map_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/forecast/panchayat/{panchayat_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Forecast Panchayat
     * @description 5-day detail with quantiles, event probabilities and derived agro-variables.
     */
    get: operations["forecast_panchayat_api_v1_forecast_panchayat__panchayat_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/observed/panchayat/{panchayat_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Observed
     * @description What happened: the Panchayat's station if it has one, else synthetic truth (mock only).
     */
    get: operations["observed_api_v1_observed_panchayat__panchayat_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/explain/{panchayat_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Explain
     * @description Top reasons this Panchayat differs from its block (placeholder static contrast until SHAP).
     */
    get: operations["explain_api_v1_explain__panchayat_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/forecast/changes/{panchayat_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Forecast Changes
     * @description What changed since the previous day's forecast.
     */
    get: operations["forecast_changes_api_v1_forecast_changes__panchayat_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/risk": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Risk
     * @description Risk level and score per Panchayat for one risk type and lead day.
     */
    get: operations["risk_api_v1_risk_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/priority": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Priority
     * @description Panchayats needing attention within the horizon, highest score first (moderate and above).
     */
    get: operations["priority_api_v1_priority_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/advisories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Advisories
     * @description Advisories filtered by status, Panchayat and issue date.
     */
    get: operations["advisories_api_v1_advisories_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/advisories/{advisory_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Advisory
     * @description One advisory with evidence and audit trail.
     */
    get: operations["advisory_api_v1_advisories__advisory_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/advisories/{advisory_id}/review": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Review
     * @description Approve, edit or reject. Appends to the audit trail and returns the updated advisory.
     */
    post: operations["review_api_v1_advisories__advisory_id__review_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/audio/{advisory_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Audio
     * @description MP3 of the advisory text, or 404 when no audio exists (the UI then falls back to browser speech).
     */
    get: operations["audio_api_v1_audio__advisory_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/farmers/{farmer_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Farmer
     * @description Demo farmer profile: Panchayat, language, crops with sowing dates.
     */
    get: operations["farmer_api_v1_farmers__farmer_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/farmers/{farmer_id}/advice": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Farmer Advice
     * @description Approved (or edited and approved) advisories for the farmer's Panchayat on this issue date.
     */
    get: operations["farmer_advice_api_v1_farmers__farmer_id__advice_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/feedback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Feedback
     * @description Farmer tapped "Did it rain?".
     */
    post: operations["feedback_api_v1_feedback_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/verification/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Summary
     * @description Model against baselines B0, B1, B2 per variable, with 95% intervals of skill.
     */
    get: operations["summary_api_v1_verification_summary_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/verification/reliability": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Reliability
     * @description Reliability diagram points for one rain event.
     */
    get: operations["reliability_api_v1_verification_reliability_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/verification/coverage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Coverage
     * @description Nominal against empirical interval coverage per variable.
     */
    get: operations["coverage_api_v1_verification_coverage_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/verification/regions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Regions
     * @description Error per held-out block.
     */
    get: operations["regions_api_v1_verification_regions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/impact": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Impact
     * @description Replay of one decision over a season: model rule against block-forecast rule.
     */
    get: operations["impact_api_v1_impact_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/data-quality": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Data Quality
     * @description Stations reporting, missing share over 30 days, stale inputs, as of an issue date.
     */
    get: operations["data_quality_api_v1_data_quality_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Advisory */
    Advisory: {
      /** Id */
      id: string;
      /**
       * Issue Date
       * Format: date
       */
      issue_date: string;
      /** Panchayat Id */
      panchayat_id: string;
      /** Block Id */
      block_id: string;
      /** Crop */
      crop: string;
      /** Stage */
      stage: string | null;
      category: components["schemas"]["Category"];
      priority: components["schemas"]["Level"];
      /**
       * Valid From
       * Format: date
       */
      valid_from: string;
      /**
       * Valid To
       * Format: date
       */
      valid_to: string;
      action: components["schemas"]["LocalizedText"];
      reason: components["schemas"]["LocalizedText"];
      fallback: components["schemas"]["LocalizedText"];
      confidence: components["schemas"]["Confidence"];
      /** Evidence */
      evidence: components["schemas"]["EvidenceItem"][];
      thresholds_status: components["schemas"]["ThresholdsStatus"];
      status: components["schemas"]["Status"];
      /** Reviewed By */
      reviewed_by: string | null;
      /** Reviewed At */
      reviewed_at: string | null;
      /** Audit */
      audit: components["schemas"]["AuditEntry"][];
      /** Audio */
      audio: {
        [key: string]: string;
      };
      data_mode: components["schemas"]["DataMode"];
      provenance: components["schemas"]["Provenance"];
      translation_status: components["schemas"]["TranslationStatus"];
    };
    /** AdvisoryList */
    AdvisoryList: {
      data_mode: components["schemas"]["DataMode"];
      provenance: components["schemas"]["Provenance"];
      /** Total */
      total: number;
      /** Items */
      items: components["schemas"]["Advisory"][];
    };
    /** AuditEntry */
    AuditEntry: {
      /**
       * At
       * Format: date-time
       */
      at: string;
      /** Actor */
      actor: string;
      /** Action */
      action: string;
      /** Note */
      note: string;
    };
    /** BlockCollection */
    BlockCollection: {
      /**
       * Type
       * @constant
       */
      type: "FeatureCollection";
      data_mode: components["schemas"]["DataMode"];
      /** Features */
      features: components["schemas"]["BlockFeature"][];
    };
    /** BlockFeature */
    BlockFeature: {
      /**
       * Type
       * @constant
       */
      type: "Feature";
      /** Geometry */
      geometry:
        components["schemas"]["PolygonGeometry"] | components["schemas"]["MultiPolygonGeometry"];
      properties: components["schemas"]["BlockProperties"];
    };
    /** BlockMapValue */
    BlockMapValue: {
      /** Block Id */
      block_id: string;
      /** Value */
      value: number | null;
    };
    /** BlockProperties */
    BlockProperties: {
      /** Block Id */
      block_id: string;
      /** Name */
      name: string;
    };
    /**
     * Category
     * @enum {string}
     */
    Category:
      | "sowing"
      | "irrigation"
      | "spray"
      | "fertilizer"
      | "harvest"
      | "heat_stress"
      | "frost"
      | "waterlogging"
      | "dry_spell"
      | "pest_disease"
      | "livestock";
    /**
     * Channel
     * @enum {string}
     */
    Channel: "app" | "whatsapp" | "ivr";
    /**
     * Confidence
     * @enum {string}
     */
    Confidence: "high" | "medium" | "low";
    /** Coverage */
    Coverage: {
      data_mode: components["schemas"]["DataMode"];
      provenance: components["schemas"]["Provenance"];
      /** Items */
      items: components["schemas"]["CoverageItem"][];
      /** Notes */
      notes: string[];
    };
    /** CoverageItem */
    CoverageItem: {
      var: components["schemas"]["Var"];
      /** Unit */
      unit: string;
      /** Nominal */
      nominal: number;
      /** Empirical */
      empirical: number | null;
      /** Mean Width */
      mean_width: number | null;
      /** N */
      n: number | null;
    };
    /**
     * DataMode
     * @enum {string}
     */
    DataMode: "mock" | "real";
    /** DataQuality */
    DataQuality: {
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      data_mode: components["schemas"]["DataMode"];
      provenance: components["schemas"]["Provenance"];
      /** Stations Total */
      stations_total: number;
      /** Stations Reporting 24H */
      stations_reporting_24h: number;
      /** Missing Share 30D */
      missing_share_30d: number | null;
      /** Stale Inputs */
      stale_inputs: components["schemas"]["StaleInput"][];
      /** Stations */
      stations: components["schemas"]["StationStatus"][];
    };
    /**
     * Decision
     * @enum {string}
     */
    Decision: "spray" | "heat_alert" | "irrigation_wait";
    /** DecisionCounts */
    DecisionCounts: {
      /** Correct */
      correct: number;
      /** Wasted Wait */
      wasted_wait: number;
      /** Washed Off */
      washed_off: number;
    };
    /** Derived */
    Derived: {
      /** Et0 Mm */
      et0_mm: number | null;
      /** Soil Moisture Frac */
      soil_moisture_frac: number | null;
      /** Thi */
      thi: number | null;
      waterlog_risk: components["schemas"]["Level"] | null;
    };
    /** EditedFields */
    EditedFields: {
      action?: components["schemas"]["LocalizedText"] | null;
      reason?: components["schemas"]["LocalizedText"] | null;
      fallback?: components["schemas"]["LocalizedText"] | null;
    };
    /**
     * Effect
     * @enum {string}
     */
    Effect:
      "warmer" | "cooler" | "wetter" | "drier" | "more_humid" | "less_humid" | "windier" | "calmer";
    /** ErrorBody */
    ErrorBody: {
      /** Code */
      code: string;
      /** Message */
      message: string;
    };
    /**
     * ErrorResponse
     * @description Every 4xx/5xx body: ``{"error": {"code", "message"}}``.
     */
    ErrorResponse: {
      error: components["schemas"]["ErrorBody"];
    };
    /** EventChange */
    EventChange: {
      /**
       * Valid Date
       * Format: date
       */
      valid_date: string;
      event: components["schemas"]["RainEvent"];
      /** Previous Prob */
      previous_prob: number | null;
      /** Current Prob */
      current_prob: number | null;
    };
    /** EventProbs */
    EventProbs: {
      /** Rain Ge 1Mm */
      rain_ge_1mm: number | null;
      /** Rain Ge 2 5Mm */
      rain_ge_2_5mm: number | null;
      /** Rain Ge 10Mm */
      rain_ge_10mm: number | null;
      /** Rain Ge 35Mm */
      rain_ge_35mm: number | null;
    };
    /** EventSummary */
    EventSummary: {
      event: components["schemas"]["RainEvent"];
      /** Pod */
      pod: number | null;
      /** Far */
      far: number | null;
      /** Csi */
      csi: number | null;
      /** Brier */
      brier: number | null;
      /** Brier Skill Vs Climatology */
      brier_skill_vs_climatology: number | null;
    };
    /** EvidenceItem */
    EvidenceItem: {
      /** Label */
      label: string;
      /** Value */
      value: string;
    };
    /** Explain */
    Explain: {
      /** Panchayat Id */
      panchayat_id: string;
      /**
       * Issue Date
       * Format: date
       */
      issue_date: string;
      /** Lead Day */
      lead_day: number;
      var: components["schemas"]["Var"];
      /** Delta Vs Block */
      delta_vs_block: number | null;
      /** Reasons */
      reasons: components["schemas"]["ExplainReason"][];
      data_mode: components["schemas"]["DataMode"];
      provenance: components["schemas"]["Provenance"];
      /** Method */
      method: string;
    };
    /** ExplainReason */
    ExplainReason: {
      /** Feature */
      feature: string;
      effect: components["schemas"]["Effect"];
      text: components["schemas"]["LocalizedText"];
    };
    /** Farmer */
    Farmer: {
      /** Farmer Id */
      farmer_id: string;
      /** Name */
      name: string;
      /** Panchayat Id */
      panchayat_id: string;
      /** Block Id */
      block_id: string;
      language: components["schemas"]["Lang"];
      /** Crops */
      crops: components["schemas"]["FarmerCrop"][];
      data_mode: components["schemas"]["DataMode"];
    };
    /** FarmerAdvice */
    FarmerAdvice: {
      /** Farmer Id */
      farmer_id: string;
      /** Panchayat Id */
      panchayat_id: string;
      /**
       * Issue Date
       * Format: date
       */
      issue_date: string;
      language: components["schemas"]["Lang"];
      data_mode: components["schemas"]["DataMode"];
      /** Items */
      items: components["schemas"]["Advisory"][];
    };
    /** FarmerCrop */
    FarmerCrop: {
      /** Crop */
      crop: string;
      /** Season */
      season: string;
      /**
       * Sowing Date
       * Format: date
       */
      sowing_date: string;
      /** Expected Harvest Date */
      expected_harvest_date: string | null;
      /** Area Fraction */
      area_fraction: number | null;
    };
    /** FeedbackRequest */
    FeedbackRequest: {
      /** Panchayat Id */
      panchayat_id: string;
      /**
       * Date
       * Format: date
       */
      date: string;
      /** Reported Rain */
      reported_rain: boolean;
      intensity: components["schemas"]["Intensity"];
      channel: components["schemas"]["Channel"];
    };
    /** FeedbackResponse */
    FeedbackResponse: {
      /** Id */
      id: string;
      /** Stored */
      stored: boolean;
      /**
       * Received At
       * Format: date-time
       */
      received_at: string;
      data_mode: components["schemas"]["DataMode"];
      feedback: components["schemas"]["FeedbackRequest"];
      message: components["schemas"]["LocalizedText"];
    };
    /** ForecastChanges */
    ForecastChanges: {
      /** Panchayat Id */
      panchayat_id: string;
      /**
       * Issue Date
       * Format: date
       */
      issue_date: string;
      /** Previous Issue Date */
      previous_issue_date: string | null;
      data_mode: components["schemas"]["DataMode"];
      provenance: components["schemas"]["Provenance"];
      /** Changes */
      changes: components["schemas"]["VarChange"][];
      /** Event Changes */
      event_changes: components["schemas"]["EventChange"][];
      /** Advice Changed */
      advice_changed: boolean | null;
      summary: components["schemas"]["LocalizedText"];
    };
    /** ForecastDay */
    ForecastDay: {
      /**
       * Date
       * Format: date
       */
      date: string;
      /** Lead Day */
      lead_day: number;
      rain: components["schemas"]["Quantiles"];
      tmax: components["schemas"]["Quantiles"];
      tmin: components["schemas"]["Quantiles"];
      rh: components["schemas"]["Quantiles"];
      wind: components["schemas"]["Quantiles"];
      prob: components["schemas"]["EventProbs"];
      derived: components["schemas"]["Derived"];
    };
    /** ForecastMap */
    ForecastMap: {
      /**
       * Issue Date
       * Format: date
       */
      issue_date: string;
      /**
       * Valid Date
       * Format: date
       */
      valid_date: string;
      /** Lead Day */
      lead_day: number;
      var: components["schemas"]["Var"];
      /** Unit */
      unit: string;
      data_mode: components["schemas"]["DataMode"];
      provenance: components["schemas"]["Provenance"];
      /** Block Layer */
      block_layer: components["schemas"]["BlockMapValue"][];
      /** Panchayat Layer */
      panchayat_layer: components["schemas"]["PanchayatMapValue"][];
    };
    /** Health */
    Health: {
      /**
       * Status
       * @constant
       */
      status: "ok";
      /** Api Version */
      api_version: string;
      data_mode: components["schemas"]["DataMode"];
    };
    /** Impact */
    Impact: {
      /** Season */
      season: string;
      decision: components["schemas"]["Decision"];
      data_mode: components["schemas"]["DataMode"];
      provenance: components["schemas"]["Provenance"];
      model: components["schemas"]["DecisionCounts"];
      block_baseline: components["schemas"]["DecisionCounts"];
      /** N Decisions */
      n_decisions: number;
      rule?: components["schemas"]["ImpactRule"] | null;
      /**
       * Notes
       * @default []
       */
      notes: string[];
    };
    /** ImpactRule */
    ImpactRule: {
      model: components["schemas"]["LocalizedText"];
      block: components["schemas"]["LocalizedText"];
    };
    /**
     * Intensity
     * @enum {string}
     */
    Intensity: "none" | "light" | "moderate" | "heavy";
    /**
     * IssueDateInfo
     * @description Why a demo issue date exists and which data window it sits in (additive, v0.1.1).
     */
    IssueDateInfo: {
      /**
       * Date
       * Format: date
       */
      date: string;
      /** Label */
      label: string;
      split: components["schemas"]["Split"];
    };
    /**
     * Lang
     * @enum {string}
     */
    Lang: "en" | "hi" | "pa";
    /**
     * Level
     * @enum {string}
     */
    Level: "low" | "moderate" | "high" | "severe";
    /**
     * LocalizedText
     * @description Text in English, Hindi and Punjabi. Hindi and Punjabi may be null when not yet written.
     */
    LocalizedText: {
      /** En */
      en: string;
      /** Hi */
      hi?: string | null;
      /** Pa */
      pa?: string | null;
    };
    /** Meta */
    Meta: {
      /** Api Version */
      api_version: string;
      data_mode: components["schemas"]["DataMode"];
      /** District */
      district: string;
      /** Available Issue Dates */
      available_issue_dates: string[];
      /** Languages */
      languages: components["schemas"]["Lang"][];
      /** Crops */
      crops: string[];
      /** Vars */
      vars: components["schemas"]["VarInfo"][];
      /** Issue Date Info */
      issue_date_info?: components["schemas"]["IssueDateInfo"][] | null;
    };
    /** MetricRow */
    MetricRow: {
      /** Name */
      name: string;
      /** Unit */
      unit: string;
      /** Model */
      model: number | null;
      /** B0 */
      b0: number | null;
      /** B1 */
      b1: number | null;
      /** B2 */
      b2: number | null;
      /** Skill Vs B0 */
      skill_vs_b0: number | null;
      /** Skill Ci95 */
      skill_ci95: number[] | null;
    };
    /** MultiPolygonGeometry */
    MultiPolygonGeometry: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "MultiPolygon";
      /** Coordinates */
      coordinates: number[][][][];
    };
    /** Observed */
    Observed: {
      /** Panchayat Id */
      panchayat_id: string;
      /**
       * From
       * Format: date
       */
      from: string;
      /**
       * To
       * Format: date
       */
      to: string;
      source: components["schemas"]["ObservedSource"];
      /** Station Id */
      station_id: string | null;
      data_mode: components["schemas"]["DataMode"];
      /** Days */
      days: components["schemas"]["ObservedDay"][];
    };
    /** ObservedDay */
    ObservedDay: {
      /**
       * Date
       * Format: date
       */
      date: string;
      /** Rain */
      rain: number | null;
      /** Tmax */
      tmax: number | null;
      /** Tmin */
      tmin: number | null;
      /** Rh */
      rh: number | null;
      /** Wind */
      wind: number | null;
    };
    /**
     * ObservedSource
     * @enum {string}
     */
    ObservedSource: "station" | "synthetic_truth" | "none";
    /** PanchayatCollection */
    PanchayatCollection: {
      /**
       * Type
       * @constant
       */
      type: "FeatureCollection";
      data_mode: components["schemas"]["DataMode"];
      /** Features */
      features: components["schemas"]["PanchayatFeature"][];
    };
    /** PanchayatFeature */
    PanchayatFeature: {
      /**
       * Type
       * @constant
       */
      type: "Feature";
      /** Geometry */
      geometry:
        components["schemas"]["PolygonGeometry"] | components["schemas"]["MultiPolygonGeometry"];
      properties: components["schemas"]["PanchayatProperties"];
    };
    /** PanchayatForecast */
    PanchayatForecast: {
      /** Panchayat Id */
      panchayat_id: string;
      /** Name */
      name: string;
      /** Block Id */
      block_id: string;
      /**
       * Issue Date
       * Format: date
       */
      issue_date: string;
      data_mode: components["schemas"]["DataMode"];
      provenance: components["schemas"]["Provenance"];
      static: components["schemas"]["StaticInfo"];
      /** Days */
      days: components["schemas"]["ForecastDay"][];
    };
    /** PanchayatMapValue */
    PanchayatMapValue: {
      /** Panchayat Id */
      panchayat_id: string;
      /** Block Id */
      block_id: string;
      /** P10 */
      p10: number | null;
      /** P50 */
      p50: number | null;
      /** P90 */
      p90: number | null;
      /** Block Value */
      block_value: number | null;
      /** Delta */
      delta: number | null;
      /** Prob Event */
      prob_event: number | null;
      event: components["schemas"]["RainEvent"] | null;
    };
    /** PanchayatProperties */
    PanchayatProperties: {
      /** Panchayat Id */
      panchayat_id: string;
      /** Name */
      name: string;
      /** Block Id */
      block_id: string;
    };
    /** Period */
    Period: {
      /**
       * Start
       * Format: date
       */
      start: string;
      /**
       * End
       * Format: date
       */
      end: string;
    };
    /** PolygonGeometry */
    PolygonGeometry: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "Polygon";
      /** Coordinates */
      coordinates: number[][][];
    };
    /** Priority */
    Priority: {
      /**
       * Issue Date
       * Format: date
       */
      issue_date: string;
      /** Horizon Days */
      horizon_days: number;
      data_mode: components["schemas"]["DataMode"];
      provenance: components["schemas"]["Provenance"];
      thresholds_status: components["schemas"]["ThresholdsStatus"];
      /** Items */
      items: components["schemas"]["PriorityItem"][];
    };
    /** PriorityItem */
    PriorityItem: {
      /** Panchayat Id */
      panchayat_id: string;
      /** Block Id */
      block_id: string;
      top_risk: components["schemas"]["RiskType"];
      level: components["schemas"]["Level"];
      /** Score */
      score: number;
      /** Crops Affected */
      crops_affected: string[];
      headline: components["schemas"]["LocalizedText"];
      /** Valid Date */
      valid_date?: string | null;
    };
    /**
     * Provenance
     * @description Where the numbers in a response come from (additive field, v0.1.1).
     *
     *     provisional: computed from the data with an interim method (corrected block forecast B1).
     *     placeholder: generated example content; numbers are not results and must not be quoted.
     *     computed: produced by the final pipeline or verification job.
     * @enum {string}
     */
    Provenance: "provisional" | "placeholder" | "computed";
    /**
     * Quantiles
     * @description p10, p50, p90 of the Panchayat forecast plus the block-level value for the same day.
     */
    Quantiles: {
      /** P10 */
      p10: number | null;
      /** P50 */
      p50: number | null;
      /** P90 */
      p90: number | null;
      /** Block */
      block: number | null;
    };
    /**
     * RainEvent
     * @enum {string}
     */
    RainEvent: "rain_ge_1mm" | "rain_ge_2_5mm" | "rain_ge_10mm" | "rain_ge_35mm";
    /** RegionItem */
    RegionItem: {
      /**
       * Region Type
       * @enum {string}
       */
      region_type: "block" | "station";
      /** Region Id */
      region_id: string;
      var: components["schemas"]["Var"];
      /** Metric */
      metric: string;
      /** Unit */
      unit: string;
      /** Model */
      model: number | null;
      /** B0 */
      b0: number | null;
      /** N */
      n: number | null;
    };
    /** Regions */
    Regions: {
      data_mode: components["schemas"]["DataMode"];
      provenance: components["schemas"]["Provenance"];
      /** Method */
      method: string;
      /** Items */
      items: components["schemas"]["RegionItem"][];
      /** Notes */
      notes: string[];
    };
    /** Reliability */
    Reliability: {
      event: components["schemas"]["RainEvent"];
      data_mode: components["schemas"]["DataMode"];
      provenance: components["schemas"]["Provenance"];
      /** Points */
      points: components["schemas"]["ReliabilityPoint"][];
      /** Notes */
      notes: string[];
    };
    /** ReliabilityPoint */
    ReliabilityPoint: {
      /** Forecast Prob */
      forecast_prob: number;
      /** Observed Freq */
      observed_freq: number | null;
      /** N */
      n: number;
    };
    /**
     * ReviewAction
     * @enum {string}
     */
    ReviewAction: "approve" | "edit" | "reject";
    /** ReviewRequest */
    ReviewRequest: {
      action: components["schemas"]["ReviewAction"];
      /** Reviewer */
      reviewer: string;
      /**
       * Note
       * @default
       */
      note: string;
      edited?: components["schemas"]["EditedFields"] | null;
    };
    /** Risk */
    Risk: {
      /**
       * Issue Date
       * Format: date
       */
      issue_date: string;
      /**
       * Valid Date
       * Format: date
       */
      valid_date: string;
      /** Lead Day */
      lead_day: number;
      type: components["schemas"]["RiskType"];
      data_mode: components["schemas"]["DataMode"];
      provenance: components["schemas"]["Provenance"];
      thresholds_status: components["schemas"]["ThresholdsStatus"];
      /** Items */
      items: components["schemas"]["RiskItem"][];
    };
    /** RiskItem */
    RiskItem: {
      /** Panchayat Id */
      panchayat_id: string;
      /** Block Id */
      block_id: string;
      level: components["schemas"]["Level"];
      /** Score */
      score: number;
    };
    /**
     * RiskType
     * @enum {string}
     */
    RiskType: "heavy_rain" | "heat" | "frost" | "waterlogging" | "dry_spell";
    /**
     * Split
     * @enum {string}
     */
    Split: "train" | "calib" | "test";
    /** StaleInput */
    StaleInput: {
      /** Input */
      input: string;
      /** Last Date */
      last_date: string | null;
      /** Days Stale */
      days_stale: number | null;
    };
    /** StaticInfo */
    StaticInfo: {
      /** Elevation M */
      elevation_m: number | null;
      /** Soil Texture */
      soil_texture: string | null;
      /** Drainage Class */
      drainage_class: string | null;
      /** Irrigated Frac */
      irrigated_frac: number | null;
    };
    /** StationStatus */
    StationStatus: {
      /** Station Id */
      station_id: string;
      /** Station Type */
      station_type: string;
      /** Block Id */
      block_id: string;
      /** Last Report */
      last_report: string | null;
      /** Reported Last 24H */
      reported_last_24h: boolean;
      /** Missing Share 30D */
      missing_share_30d: number | null;
      /** Flagged Share 30D */
      flagged_share_30d: number | null;
    };
    /**
     * Status
     * @enum {string}
     */
    Status: "draft" | "approved" | "edited" | "rejected";
    /**
     * ThresholdsStatus
     * @enum {string}
     */
    ThresholdsStatus: "placeholder" | "reviewed";
    /**
     * TranslationStatus
     * @enum {string}
     */
    TranslationStatus: "needs_native_review" | "reviewed";
    /**
     * Var
     * @enum {string}
     */
    Var: "rain" | "tmax" | "tmin" | "rh" | "wind";
    /** VarChange */
    VarChange: {
      /**
       * Valid Date
       * Format: date
       */
      valid_date: string;
      var: components["schemas"]["Var"];
      /** Previous P50 */
      previous_p50: number | null;
      /** Current P50 */
      current_p50: number | null;
      /** Delta */
      delta: number | null;
      /** Material */
      material: boolean;
    };
    /** VarInfo */
    VarInfo: {
      var: components["schemas"]["Var"];
      /** Unit */
      unit: string;
    };
    /** VariableSummary */
    VariableSummary: {
      var: components["schemas"]["Var"];
      /** N */
      n: number | null;
      /** Metrics */
      metrics: components["schemas"]["MetricRow"][];
    };
    /** VerificationSummary */
    VerificationSummary: {
      data_mode: components["schemas"]["DataMode"];
      provenance: components["schemas"]["Provenance"];
      /** Method */
      method: string;
      period: components["schemas"]["Period"];
      /** Variables */
      variables: components["schemas"]["VariableSummary"][];
      /** Events */
      events: components["schemas"]["EventSummary"][];
      /** Block Mean Error */
      block_mean_error: {
        [key: string]: number | null;
      };
      /** Notes */
      notes: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  meta_api_v1_meta_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Meta"];
        };
      };
    };
  };
  panchayats_api_v1_geo_panchayats_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PanchayatCollection"];
        };
      };
    };
  };
  blocks_api_v1_geo_blocks_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BlockCollection"];
        };
      };
    };
  };
  forecast_map_api_v1_forecast_map_get: {
    parameters: {
      query: {
        /** @description Issue date, one of /meta.available_issue_dates */
        issue_date: string;
        /** @description Lead day, 1 = tomorrow */
        lead_day: number;
        var: components["schemas"]["Var"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ForecastMap"];
        };
      };
      /** @description Unknown id or issue date */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  forecast_panchayat_api_v1_forecast_panchayat__panchayat_id__get: {
    parameters: {
      query: {
        /** @description Issue date, one of /meta.available_issue_dates */
        issue_date: string;
      };
      header?: never;
      path: {
        panchayat_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PanchayatForecast"];
        };
      };
      /** @description Unknown id or issue date */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  observed_api_v1_observed_panchayat__panchayat_id__get: {
    parameters: {
      query: {
        from: string;
        to: string;
      };
      header?: never;
      path: {
        panchayat_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Observed"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unknown id or issue date */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  explain_api_v1_explain__panchayat_id__get: {
    parameters: {
      query: {
        /** @description Issue date, one of /meta.available_issue_dates */
        issue_date: string;
        /** @description Lead day, 1 = tomorrow */
        lead_day: number;
        var: components["schemas"]["Var"];
      };
      header?: never;
      path: {
        panchayat_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Explain"];
        };
      };
      /** @description Unknown id or issue date */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not computed for real data yet */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  forecast_changes_api_v1_forecast_changes__panchayat_id__get: {
    parameters: {
      query: {
        /** @description Issue date, one of /meta.available_issue_dates */
        issue_date: string;
      };
      header?: never;
      path: {
        panchayat_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ForecastChanges"];
        };
      };
      /** @description Unknown id or issue date */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  risk_api_v1_risk_get: {
    parameters: {
      query: {
        issue_date: string;
        lead_day: number;
        type: components["schemas"]["RiskType"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Risk"];
        };
      };
      /** @description Unknown id or issue date */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  priority_api_v1_priority_get: {
    parameters: {
      query: {
        issue_date: string;
        horizon_days?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Priority"];
        };
      };
      /** @description Unknown id or issue date */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  advisories_api_v1_advisories_get: {
    parameters: {
      query?: {
        status?: components["schemas"]["Status"] | null;
        panchayat_id?: string | null;
        issue_date?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdvisoryList"];
        };
      };
      /** @description Unknown id or issue date */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  advisory_api_v1_advisories__advisory_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        advisory_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Advisory"];
        };
      };
      /** @description Unknown id or issue date */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  review_api_v1_advisories__advisory_id__review_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        advisory_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReviewRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Advisory"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unknown id or issue date */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  audio_api_v1_audio__advisory_id__get: {
    parameters: {
      query: {
        lang: components["schemas"]["Lang"];
      };
      header?: never;
      path: {
        advisory_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description MP3 of the advisory text */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "audio/mpeg": unknown;
        };
      };
      /** @description Unknown id or issue date */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  farmer_api_v1_farmers__farmer_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        farmer_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Farmer"];
        };
      };
      /** @description Unknown id or issue date */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  farmer_advice_api_v1_farmers__farmer_id__advice_get: {
    parameters: {
      query: {
        issue_date: string;
      };
      header?: never;
      path: {
        farmer_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FarmerAdvice"];
        };
      };
      /** @description Unknown id or issue date */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  feedback_api_v1_feedback_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FeedbackRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeedbackResponse"];
        };
      };
      /** @description Unknown id or issue date */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  summary_api_v1_verification_summary_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VerificationSummary"];
        };
      };
      /** @description Unknown id or issue date */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not computed for real data yet */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  reliability_api_v1_verification_reliability_get: {
    parameters: {
      query: {
        event: components["schemas"]["RainEvent"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Reliability"];
        };
      };
      /** @description Unknown id or issue date */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not computed for real data yet */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  coverage_api_v1_verification_coverage_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Coverage"];
        };
      };
      /** @description Unknown id or issue date */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not computed for real data yet */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  regions_api_v1_verification_regions_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Regions"];
        };
      };
      /** @description Unknown id or issue date */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not computed for real data yet */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  impact_api_v1_impact_get: {
    parameters: {
      query?: {
        season?: string;
        decision?: components["schemas"]["Decision"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Impact"];
        };
      };
      /** @description Unknown id or issue date */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not computed for real data yet */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  data_quality_api_v1_data_quality_get: {
    parameters: {
      query?: {
        issue_date?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DataQuality"];
        };
      };
      /** @description Unknown id or issue date */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Invalid parameters */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
